# Generated by Django 5.1a1 on 2024-06-24 18:34

import colorfield.fields
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgenciaFomento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sigla', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cor', colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='Pesquisador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('data_nascimento', models.DateField()),
                ('foto_perfil', models.CharField(blank=True, max_length=255, null=True)),
                ('curriculo_lattes', models.CharField(max_length=255, null=True)),
                ('full_name', models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Concat('nome', models.Value(' '), 'sobrenome'), output_field=models.CharField(max_length=510))),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('objetivo', models.TextField()),
                ('descricao', models.TextField()),
                ('data_criacao', models.DateField()),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('valor_solicitado', models.DecimalField(decimal_places=2, max_digits=11)),
                ('cancelado', models.BooleanField(default=False)),
                ('agencias_fomento', models.ManyToManyField(blank=True, related_name='projeto_set', to='projac.agenciafomento')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projeto_set', to='projac.area')),
            ],
        ),
        migrations.CreateModel(
            name='ProducaoAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(max_length=255)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producoes_academicas', to='projac.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='PesquisadorProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=255)),
                ('horas', models.IntegerField(null=True)),
                ('pesquisador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='projac.pesquisador')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesquisadores', to='projac.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subarea_set', to='projac.area')),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='subarea',
            field=models.ManyToManyField(blank=True, related_name='projeto_set', to='projac.subarea'),
        ),
        migrations.CreateModel(
            name='ValorArrecadado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=11)),
                ('descricao', models.TextField()),
                ('data', models.DateField()),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_arrecadados', to='projac.projeto')),
            ],
        ),
    ]
